### ISSUE TITLE
Test for the example router project

### ISSUE THREAD

**Issue by ggbbr** [includeos/IncludeOS#2147]
Readme for router project is empty. The router project creates a new router and arranges a routing table for it. But how should I test the function of the router? The running results are as bellow:
![image](https://user-images.githubusercontent.com/27666755/56800532-d06bb180-684d-11e9-9671-f1db33519ff8.png)
What should I do?

**Comment by fwsGonzo** [comment]
You need to configure a network with routes to and from your VM.
https://wiki.qemu.org/index.php/Documentation/Networking

**Comment by ggbbr** [comment]
Thanks so much for your replying. But i am little confused, do you mind being more specific? I still dont have a clue to test the router project.

**Comment by ggbbr** [comment]
I boot the /test/net/integration/router project for testing router, but it also just creates and prepares a router. How can I test the router? The results for running router are as bellow
![image](https://user-images.githubusercontent.com/27666755/56848337-3e7daa80-691a-11e9-827f-1d1beb3c5da8.png)

**Comment by fwsGonzo** [comment]
Well the routing is moving packets from one network device to another (or one vlan to another), essentially. So you need at least 2 network interfaces, and then you need to use a linux terminal to create routes for the interfaces. I honestly don't recommend using Qemu for routing anything. It uses tap devices which are crazy hard to work with for no particular reason. Just linux things. I would use something like VMware workstation which sets up interfaces for you, and you can configure the networks in a GUI.

As for the router test, I didnt write it, so I dont really know what its supposed to do, but maybe it uses network namespaces to separate the networks properly, so that linux doesnt short-circuit the packets?

**Comment by ggbbr** [comment]
Thank you for your help. I took your advice, I created a Unikernel Web Serveice to answer the request from Linux via my router, and it works. Thank you again.
