### ISSUE TITLE
RDRAND/RDSEED instructions not available...

### ISSUE THREAD

**Issue by tweekley49** [includeos/IncludeOS#2175]
Going to boot and I am getting an error stating 
"RDRAND/RDSEED instructions not available" and then it shuts down. 
I am on Ubuntu 18.04 and have no problem Hello World and demo_service...any ideas?
I am trying to boot Linpack if that helps any. Thanks!

**Comment by fwsGonzo** [comment]
If you know how to put the OS in editable mode you could just use my "more recent" branch: https://github.com/fwsGonzo/IncludeOS

If you build the OS in editable mode, services should pick that up automatically. It's a bit more involved than it used to be, but it works out for the most part.


Otherwise, the shortest path to success here is to disable the FOR_PRODUCTION cmake option. Personally I'm a big fan of ccmake for that, which can be installed from the `cmake-curses-gui` package. Then, go into the build folder and type `ccmake ..`, disable the option, press C and then Q to exit the GUI.

**Comment by tweekley49** [comment]
Worked perfectly, thanks! (Went with the cmake-curses-gui method).
