### ISSUE TITLE
Conan Misconfiguration

### ISSUE THREAD

**Issue by Krayfighter** [includeos/IncludeOS#2221]
I am on arch linux, and downloaded conan from AUR and follow the steps in README.md but got to a point where conan would not run the install command  {
conan install ../hello_world -pr <your_conan_profile>
}
giving the error {
ERROR: Error reading 'clang-6.0-linux-x86_64' profile: ConfigParser: Unrecognized field 'build_requires'
}
doing research I found the in the toolchain file (or whatever it is called in conan projects) was using the deprecated [build_requires] attribute instead of the [tool_requires] which is the only working option as of conan 2.x and that as I tried to fix issues with the file (not knowing how conan works) I could not get the project to compile

**Comment by bonanDong** [comment]
I encountered the same problem. Has this problem been solved?
if sloved,please tell me.
thank you

**Comment by chetanpandey1266** [comment]
Any fix for this?

**Comment by alfreb** [comment]
The builds are broken since conan 2 deprecated conan 1 files. We might support conanfiles in the future, but currently we're working on a nix toolchain, which is in progress - `nix-build` in the source root is currently the closest thing we have to a working buld. Pay attention to nix-related commits for following this work.
